"""Deterministic close-out transaction for metadata-managed Sopify plans."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
import re
import shutil
from pathlib import Path
from typing import Mapping

from ._yaml import YamlParseError, load_yaml
from .kb import ensure_blueprint_index
from .knowledge_layout import resolve_path
from .knowledge_sync import KNOWLEDGE_SYNC_KEYS, knowledge_sync_targets, parse_knowledge_sync
from .models import KbArtifact, PlanArtifact, RuntimeConfig
from .plan_registry import PlanRegistryError, remove_plan_entry
from .state import StateStore, iso_now

_REQUIRED_METADATA_KEYS = (
    "plan_id",
    "feature_key",
    "level",
    "lifecycle_state",
    "knowledge_sync",
    "archive_ready",
)
_SUPPORTED_LEVELS = {"light", "standard", "full"}
_SUPPORTED_LIFECYCLE_STATES = {"active", "ready_for_verify"}
_FRONT_MATTER_RE = re.compile(r"\A---\n(?P<front>.*?)\n---\n(?P<body>.*)\Z", re.DOTALL)
@dataclass(frozen=True)
class ManagedPlanDocument:
    """Normalized metadata view for a runtime-managed plan document."""

    plan_dir: Path
    relative_plan_dir: str
    metadata_path: Path
    relative_metadata_path: str
    plan_id: str
    feature_key: str
    level: str
    lifecycle_state: str
    knowledge_sync: Mapping[str, str]
    archive_ready: bool
    front_matter: str
    body: str
    raw_text: str


@dataclass(frozen=True)
class FinalizeResult:
    """Structured result of the finalize transaction."""

    archived_plan: PlanArtifact | None
    kb_artifact: KbArtifact | None
    notes: tuple[str, ...]
    registry_updated: bool = False


@dataclass(frozen=True)
class _KnowledgeSyncStatus:
    blocked_reason: str | None
    notes: tuple[str, ...]


def finalize_plan(
    *,
    config: RuntimeConfig,
    state_store: StateStore,
    current_plan: PlanArtifact | None,
) -> FinalizeResult:
    """Finalize the active metadata-managed plan into history.

    First version boundary:
    - only metadata-managed plans generated by the new runtime are supported
    - explicit `~go finalize` is the close-out checkpoint
    - legacy plans are rejected instead of being auto-migrated
    """
    if current_plan is None:
        return FinalizeResult(
            archived_plan=None,
            kb_artifact=None,
            notes=(_text(config.language, "no_active_plan"),),
        )

    plan_dir = config.workspace_root / current_plan.path
    if not plan_dir.exists() or not plan_dir.is_dir():
        return FinalizeResult(
            archived_plan=None,
            kb_artifact=None,
            notes=(_text(config.language, "missing_plan_dir", path=current_plan.path),),
        )

    managed_plan = _load_managed_plan(plan_dir, config=config)
    if managed_plan is None:
        return FinalizeResult(
            archived_plan=None,
            kb_artifact=None,
            notes=(_text(config.language, "legacy_unsupported"),),
        )

    if managed_plan.plan_id != current_plan.plan_id:
        return FinalizeResult(
            archived_plan=None,
            kb_artifact=None,
            notes=(
                _text(
                    config.language,
                    "metadata_mismatch",
                    state_plan_id=current_plan.plan_id,
                    document_plan_id=managed_plan.plan_id,
                ),
            ),
        )

    contract_status = _evaluate_knowledge_sync(
        config=config,
        managed_plan=managed_plan,
        created_at=current_plan.created_at,
    )
    if contract_status.blocked_reason is not None:
        return FinalizeResult(
            archived_plan=None,
            kb_artifact=None,
            notes=(*contract_status.notes, contract_status.blocked_reason),
        )

    archive_dir = _archive_target_dir(config=config, plan_id=managed_plan.plan_id)
    if archive_dir.exists():
        return FinalizeResult(
            archived_plan=None,
            kb_artifact=None,
            notes=(
                _text(
                    config.language,
                    "archive_exists",
                    path=str(archive_dir.relative_to(config.workspace_root)),
                ),
            ),
        )

    archive_dir.parent.mkdir(parents=True, exist_ok=True)
    shutil.move(str(plan_dir), str(archive_dir))

    archived_metadata_path = archive_dir / managed_plan.metadata_path.name
    archived_text = _render_document(
        _replace_front_matter_fields(
            managed_plan.front_matter,
            {
                "lifecycle_state": "archived",
                "archive_ready": "true",
            },
        ),
        managed_plan.body,
    )
    archived_metadata_path.write_text(archived_text, encoding="utf-8")

    archived_plan = PlanArtifact(
        plan_id=current_plan.plan_id,
        title=current_plan.title,
        summary=current_plan.summary,
        level=current_plan.level,
        path=str(archive_dir.relative_to(config.workspace_root)),
        files=_archived_files(current_plan=current_plan, archive_dir=archive_dir, workspace_root=config.workspace_root),
        created_at=current_plan.created_at,
    )

    history_index_path = _update_history_index(config=config, archived_plan=archived_plan)
    ensure_blueprint_index(config)
    readme_path = resolve_path(config=config, key="blueprint_index")

    registry_notes: tuple[str, ...] = ()
    registry_updated = False
    try:
        registry_updated = remove_plan_entry(config=config, plan_id=current_plan.plan_id)
    except PlanRegistryError:
        registry_notes = (_text(config.language, "registry_sync_failed"),)

    state_store.reset_active_flow()

    kb_files = tuple(
        path
        for path in (
            str(readme_path.relative_to(config.workspace_root)),
            str(history_index_path.relative_to(config.workspace_root)),
        )
    )
    notes = (
        *contract_status.notes,
        _text(config.language, "archived", path=archived_plan.path),
        _text(config.language, "state_cleared"),
        *registry_notes,
    )
    return FinalizeResult(
        archived_plan=archived_plan,
        kb_artifact=KbArtifact(mode=config.kb_init, files=kb_files, created_at=iso_now()),
        notes=notes,
        registry_updated=registry_updated,
    )


def _load_managed_plan(plan_dir: Path, *, config: RuntimeConfig) -> ManagedPlanDocument | None:
    metadata_path = _pick_metadata_file(plan_dir)
    if metadata_path is None:
        return None

    raw_text = metadata_path.read_text(encoding="utf-8")
    match = _FRONT_MATTER_RE.match(raw_text)
    if match is None:
        return None

    front_matter = match.group("front")
    body = match.group("body")
    try:
        metadata = load_yaml(front_matter)
    except YamlParseError:
        return None
    if not isinstance(metadata, Mapping):
        return None
    if any(key not in metadata for key in _REQUIRED_METADATA_KEYS):
        return None
    knowledge_sync = parse_knowledge_sync(metadata.get("knowledge_sync"))
    if knowledge_sync is None:
        return None

    level = str(metadata["level"])
    lifecycle_state = str(metadata["lifecycle_state"])
    if level not in _SUPPORTED_LEVELS or lifecycle_state not in _SUPPORTED_LIFECYCLE_STATES:
        return None

    return ManagedPlanDocument(
        plan_dir=plan_dir,
        relative_plan_dir=str(plan_dir.relative_to(config.workspace_root)),
        metadata_path=metadata_path,
        relative_metadata_path=str(metadata_path.relative_to(config.workspace_root)),
        plan_id=metadata["plan_id"],
        feature_key=metadata["feature_key"],
        level=level,
        lifecycle_state=lifecycle_state,
        knowledge_sync=knowledge_sync,
        archive_ready=_parse_bool(str(metadata["archive_ready"])),
        front_matter=front_matter,
        body=body,
        raw_text=raw_text,
    )


def _pick_metadata_file(plan_dir: Path) -> Path | None:
    for filename in ("plan.md", "tasks.md"):
        candidate = plan_dir / filename
        if candidate.exists() and candidate.is_file():
            return candidate
    return None


def _parse_bool(value: str) -> bool:
    return value.strip().lower() == "true"


def _replace_front_matter_fields(front_matter: str, updates: Mapping[str, str]) -> str:
    lines = front_matter.splitlines()
    remaining = dict(updates)
    for index, line in enumerate(lines):
        if not line or line.startswith(" ") or ":" not in line:
            continue
        key, _, _ = line.partition(":")
        key = key.strip()
        if key in remaining:
            lines[index] = f"{key}: {remaining.pop(key)}"
    if remaining:
        missing = ", ".join(sorted(remaining))
        raise ValueError(f"Missing expected metadata keys while updating front matter: {missing}")
    return "\n".join(lines)


def _render_document(front_matter: str, body: str) -> str:
    return f"---\n{front_matter}\n---\n{body}"


def _evaluate_knowledge_sync(
    *,
    config: RuntimeConfig,
    managed_plan: ManagedPlanDocument,
    created_at: str,
) -> _KnowledgeSyncStatus:
    plan_created_at = _parse_created_at(created_at)
    plan_document_time = datetime.fromtimestamp(managed_plan.metadata_path.stat().st_mtime, tz=plan_created_at.tzinfo)
    reference_time = max(plan_created_at, plan_document_time)
    targets = knowledge_sync_targets(config=config)
    changed_files: list[str] = []
    review_pending: list[str] = []
    required_missing: list[str] = []

    for key in KNOWLEDGE_SYNC_KEYS:
        mode = managed_plan.knowledge_sync[key]
        if mode == "skip":
            continue
        path = targets[key]
        updated = path.exists() and datetime.fromtimestamp(path.stat().st_mtime, tz=reference_time.tzinfo) > reference_time
        relative_path = str(path.relative_to(config.workspace_root))
        if updated:
            changed_files.append(relative_path)
            continue
        if mode == "required":
            required_missing.append(relative_path)
        else:
            review_pending.append(relative_path)

    if required_missing:
        return _KnowledgeSyncStatus(
            blocked_reason=_text(config.language, "knowledge_sync_required_blocked", paths=", ".join(required_missing)),
            notes=(),
        )

    notes: list[str] = []
    if changed_files:
        notes.append(_text(config.language, "knowledge_sync_updated", paths=", ".join(changed_files)))
    if review_pending:
        notes.append(_text(config.language, "knowledge_sync_review_warning", paths=", ".join(review_pending)))

    return _KnowledgeSyncStatus(
        blocked_reason=None,
        notes=tuple(notes),
    )


def _parse_created_at(value: str) -> datetime:
    if value:
        return datetime.fromisoformat(value.replace("Z", "+00:00"))
    return datetime.now().astimezone()


def _archive_target_dir(*, config: RuntimeConfig, plan_id: str) -> Path:
    archive_month = datetime.now().strftime("%Y-%m")
    return resolve_path(config=config, key="history_root") / archive_month / plan_id


def _archived_files(*, current_plan: PlanArtifact, archive_dir: Path, workspace_root: Path) -> tuple[str, ...]:
    source_root = current_plan.path.rstrip("/")
    target_root = str(archive_dir.relative_to(workspace_root))
    archived_files: list[str] = []
    for path in current_plan.files:
        if path.startswith(source_root):
            archived_files.append(path.replace(source_root, target_root, 1))
        else:
            archived_files.append(path)
    return tuple(archived_files)


def _update_history_index(*, config: RuntimeConfig, archived_plan: PlanArtifact) -> Path:
    history_index = resolve_path(config=config, key="history_root") / "index.md"
    history_index.parent.mkdir(parents=True, exist_ok=True)
    existing = history_index.read_text(encoding="utf-8") if history_index.exists() else _history_index_stub(config.language)
    updated = _render_history_index(existing, archived_plan=archived_plan, language=config.language)
    if updated != existing:
        history_index.write_text(updated, encoding="utf-8")
    return history_index


def _render_history_index(existing: str, *, archived_plan: PlanArtifact, language: str) -> str:
    entry = _history_entry(archived_plan=archived_plan, language=language)
    if language == "en-US":
        header = "# Change History Index\n\nRecords completed plan archives for future lookup.\n\n## Index\n\n"
        placeholder = "No archived plans yet."
    else:
        header = "# 变更历史索引\n\n记录已归档的方案，便于后续查询。\n\n## 索引\n\n"
        placeholder = "当前暂无已归档方案。"

    body = existing
    if "## Index" in existing or "## 索引" in existing:
        _, _, remainder = existing.partition("## Index\n\n" if language == "en-US" else "## 索引\n\n")
        body = remainder
    lines = [line for line in body.splitlines() if line.strip() and line.strip() != placeholder]
    lines = [line for line in lines if archived_plan.plan_id not in line]
    lines.insert(0, entry)
    return header + "\n".join(lines) + "\n"


def _history_entry(*, archived_plan: PlanArtifact, language: str) -> str:
    date_text = datetime.now().strftime("%Y-%m-%d")
    link = archived_plan.path.removeprefix(".sopify-skills/history/")
    if language == "en-US":
        return f"- `{date_text}` [`{archived_plan.plan_id}`]({link}/) - {archived_plan.level} - {archived_plan.title}"
    return f"- `{date_text}` [`{archived_plan.plan_id}`]({link}/) - {archived_plan.level} - {archived_plan.title}"


def _history_index_stub(language: str) -> str:
    if language == "en-US":
        return "# Change History Index\n\nRecords completed plan archives for future lookup.\n\n## Index\n\nNo archived plans yet.\n"
    return "# 变更历史索引\n\n记录已归档的方案，便于后续查询。\n\n## 索引\n\n当前暂无已归档方案。\n"

def _text(language: str, key: str, **kwargs: str) -> str:
    messages = {
        "en-US": {
            "no_active_plan": "No active metadata-managed plan is available to finalize",
            "missing_plan_dir": "Active plan directory is missing: {path}",
            "legacy_unsupported": "Finalize only supports metadata-managed plans generated by the new runtime; legacy plans are not auto-migrated",
            "metadata_mismatch": "Plan metadata mismatch: state plan_id={state_plan_id} but document plan_id={document_plan_id}",
            "archive_exists": "Archive target already exists: {path}",
            "archived": "Plan archived to {path}",
            "state_cleared": "Active runtime state cleared",
            "registry_sync_failed": "The active plan was archived, but the plan registry could not be updated automatically",
            "knowledge_sync_updated": "Detected knowledge_sync document updates after plan creation: {paths}",
            "knowledge_sync_review_warning": "Knowledge_sync review reminder: review items were not updated after plan creation: {paths}",
            "knowledge_sync_required_blocked": "Finalize blocked: required knowledge_sync documents were not updated after plan creation: {paths}",
        },
        "zh-CN": {
            "no_active_plan": "当前没有可收口的 metadata-managed 活动方案",
            "missing_plan_dir": "当前活动方案目录不存在：{path}",
            "legacy_unsupported": "finalize 仅支持新 runtime 生成的 metadata-managed plan，旧遗留 plan 不会被自动迁移",
            "metadata_mismatch": "方案元数据不一致：state plan_id={state_plan_id}，文档 plan_id={document_plan_id}",
            "archive_exists": "归档目标已存在：{path}",
            "archived": "方案已归档到 {path}",
            "state_cleared": "已清理活动运行时状态",
            "registry_sync_failed": "活动 plan 已归档，但 plan registry 未能自动同步更新",
            "knowledge_sync_updated": "已检测到 plan 创建后的 knowledge_sync 文档更新：{paths}",
            "knowledge_sync_review_warning": "knowledge_sync 复核提醒：以下 review 文档在 plan 创建后尚未更新：{paths}",
            "knowledge_sync_required_blocked": "收口被阻断：以下 knowledge_sync.required 文档在 plan 创建后尚未更新：{paths}",
        },
    }
    locale = "en-US" if language == "en-US" else "zh-CN"
    template = messages[locale][key]
    return template.format(**kwargs)
